
[mgr]
prepend_keymap = [
    {  on   = "l", run  = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "T", run = 'shell "$SHELL" --block', desc = "Open terminal at current dir" }
]

